name: Build
on: [push, pull_request]
jobs:
  build_windows:
    strategy:
      matrix:
        target: [ x86_64, aarch64 ]
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-rust
      - run: rustup target add ${{ matrix.target }}-pc-windows-msvc
      - run: cargo build --release --target ${{ matrix.target }}-pc-windows-msvc
      - uses: actions/upload-artifact@v3
        with:
          name: Windows ${{ matrix.target }}
          path: |
            target/${{ matrix.target }}-pc-windows-msvc/release/raap.exe
            target/${{ matrix.target }}-pc-windows-msvc/release/raap.pdb

  build_macos:
    strategy:
      matrix:
        target: [ x86_64, aarch64 ]
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-rust
      - run: rustup target add ${{ matrix.target }}-apple-darwin
      - run: cargo build --release --target ${{ matrix.target }}-apple-darwin
      - uses: actions/upload-artifact@v3
        with:
          name: MacOS ${{ matrix.target }}
          path: |
            target/${{ matrix.target }}-apple-darwin/release/raap